[workspace]
resolver = "2"
members = [
    "src/flexwage_backend",
]

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.13"
serde = { version = "1.0", features = ["derive"] }
ic-stable-structures = "0.6"
ic-cdk-timers = "0.7"
